name: Deploy
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: ssh 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd ~/blog
          git pull
          ~/.local/bin/mkdocs build --site-dir /var/www/blog
